[project]
name = "skillbadge"
description = "Unique voting contract for project 03"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.skillbadge]
path = "contracts/skillbadge.clar"

[repl.analysis]
passes = ["check_checker"]
